### ISSUE TITLE
ip故障时不会重新解析

### ISSUE THREAD

**Issue by HanadaLee** [zanjie1999/tcp-over-websocket#13]
目前使用一段时间后发现只会在启动的时候解析ip，后面即便ip无法连接或者dns记录更新也不会做任何变动。对于基于DNS调度的CDN很不友好（目前除了cloudflare和fastly，其他CDN厂商基本都是DNS调度，ip经常可能会出现上下架或者故障切换等情况）
建议做一下改动：
1、记录解析的ttl，作为ip有效期，本次tcp断开之后重新查询dns记录，获取新ip
2、ip解析失败3次以上，重新查询ip地址

**Comment by zanjie1999** [comment]
设计如此，因为经常因为dns问题导致污染连接失败，或是因为dns走本程序导致解析到了更远的ip，所以在启动时获取ip并且一直用的功能

等有空了可以实现根据ttl，自动重新获取dns替换当前固定的ip（ip上下架应该会遵循ttl吧）
连接失败三次的话，在做http转发的时候一瞬间就会有几十个请求（，这个暂时不考虑

**Comment by HanadaLee** [comment]
不过dns设计之初就是为了实现动态ip的，如果固定ip的话直接填ip不更好，我现在是用shell脚本监控输出日志，然后发现连接失败就把进程重启

**Comment by zanjie1999** [comment]
搞定，另外go获取dns记录的ttl，只能使用miekg/dns这个库，别无它法，chatgpt与new bing都会让你用LookupTXT来获取，实际LookupTXT是用来获取域名的txt记录的
