### ISSUE TITLE
CDN优选IP需求

### ISSUE THREAD

**Issue by grxchhlrlxsxyz** [zanjie1999/tcp-over-websocket#14]
现在的是靠dns去解析得到IP，这个IP不一定适合自己网络使用。比如CF，优选针对自己的网络好用的IP。

现在尝试hosts文件内添加强制解析，但还是调用53端口去解析。

可否做个参数 如以下

tcp2ws ws://1.1.1.1:端口 使用的域名 监听端口

1.1.1.1代表优选ip

**Comment by zanjie1999** [comment]
有个比较简单的方法，改本地的dns服务器的dnsmasq或是他对应的hosts，至于直接指定ip这个有空可以做一下

**Comment by grxchhlrlxsxyz** [comment]
hosts，我已经试了。不行，还是默认走53端口去解析。

**Comment by zanjie1999** [comment]
程序不会走hosts，需要你本地的dns服务区解析你本地的hosts

**Comment by zanjie1999** [comment]
实现啦，用正则写了个hosts文件解析器，应该能覆盖到常见的hosts格式，不过Windows没有测试过不知道能不能读到hosts文件
