### ISSUE TITLE
能像chisel有--backend功能吗?

### ISSUE THREAD

**Issue by 189er** [zanjie1999/tcp-over-websocket#17]
chisel  server -v --host 127.0.0.1 -p 80 --socks5 --backend http://127.0.0.1:5244/

https://github.com/jpillora/chisel/releases/download/v1.8.1/chisel_1.8.1_windows_amd64.gz

**Comment by 189er** [comment]
不知道PATH能指定吗?

**Comment by zanjie1999** [comment]
没有，也不打算做

我比较偏向于把这个套在一个nginx后面，nginx负责干backend的活，提供一个看起来很正常的网站展示，nginx能提供更多样化的安全web服务（比如http2啦），并且返回头部看起来更像是你搭了一个正经网站而不是干其他事

如果只需要简单的伪装，你可以在程序旁边放一个index.html，在里面写入内容以便在浏览器访问时展示，访问任何路径都会返回这个文件，你也可以通过js实现一些重定向

**Comment by zanjie1999** [comment]
当然，欢迎pr，但注意向下兼容性
