### ISSUE TITLE
建议区分server和client功能，让工具适应更广泛的场景

### ISSUE THREAD

**Issue by ruhuansanmei** [zanjie1999/tcp-over-websocket#18]
内网地址不能通过公网ip或者域名代理的情况下，你这个工具不适用；比如如下场景:
在家里电脑上启动一个网站服务为localhost:3000, 现在有一个公网服务器xxx.xxx.xxx.xxx,如何使用本工具使得互联网用户能通过xxx.xxx.xxx.xxx来访问到这个站点？
所以我建议可以有一个ws server来专门做中继，然后在访问端和被代理端分别开客户端来进行连通：

![f6b94dec2e13960d2ec60a8ef023f5d](https://github.com/zanjie1999/tcp-over-websocket/assets/17924820/07b2b194-d9d0-4c5a-a873-1988dcfd8586)

**Comment by zanjie1999** [comment]
此工具并不适用于你所说的无公网ip内网穿透（此内网非彼内网），而是用于像“政务云”那样的内网利用http web服务多层反向代理对TCP或UDP进行转发（是的，那些机自身是完全无法访问互联网的），既可以隐秘的过层层防火墙也可以躲避检查
另外，你要找的工具是不是 frp

**Comment by zanjie1999** [comment]
另外关于你提到的操作，我更偏向于使用webrtc，因为目前就算移动大内网也有nat1，只有你把光猫upnp开一下，udp组网传输完全没问题
