### ISSUE TITLE
你好tcp2wsSparkleClose错误怎么办

### ISSUE THREAD

**Issue by saber0000** [zanjie1999/tcp-over-websocket#23]
这个是 前端和 后端 通过tcp2ws直连成功了， 然后在浏览器刷新一下就提示这个关闭了 是哪里设置错了

**Comment by zanjie1999** [comment]
你日志呢？

**Comment by saber0000** [comment]
![捕获](https://github.com/zanjie1999/tcp-over-websocket/assets/30066065/607b7caf-1446-49ae-bf8f-deda5a675260)
是这个日志吗

**Comment by zanjie1999** [comment]
“forcibly closed by the remote host”
你的连接被掐了

**Comment by saber0000** [comment]
好我检查检查 谢谢
