### ISSUE TITLE
端口重用问题

### ISSUE THREAD

**Issue by saberya** [zanjie1999/tcp-over-websocket#24]
没太get到这里的用法
> tcp2ws wss://链接 8888
执行这个监听8888时，这个端口被这个进程占用，本地还怎么创建与这个端口的连接
端口不能重用才对

**Comment by zanjie1999** [comment]
比如你22端口有个ssh，  
tcp2ws 22 55555
服务端就完成了,假设服务器ip是1.2.3.4  
然后你去客户端
tcp2ws ws://1.2.3.4:55555 222
ssh -p 222 127.0.0.1

**Comment by saberya** [comment]
> 222



> 比如你22端口有个ssh， tcp2ws 22 55555 服务端就完成了,假设服务器ip是1.2.3.4 然后你去客户端 tcp2ws ws://1.2.3.4:55555 222 ssh -p 222 127.0.0.1

居然回复了，我这里本地是一个tcp连接，会指定端口，比如8888。我本地会启动一个代理进程，连接远端代理服务器，远端代理服务器接收ws协议，所以我本地的代理进程会监听8888端口，把8888端口的流量转发远端代理服务器。然后问题就来了，我本地监听8888端口后，这个端口就不能被其他tcp使用了。我本来是想通过tunnel方式去解决，但是太麻烦了，不想这么做。所以这会没找到太好的方法

**Comment by saberya** [comment]
> 比如你22端口有个ssh， tcp2ws 22 55555 服务端就完成了,假设服务器ip是1.2.3.4 然后你去客户端 tcp2ws ws://1.2.3.4:55555 222 ssh -p 222 127.0.0.1
这里net.Listen("tcp", 222)
然后本地再使用222这个端口连接，不会报这个吗？
> Address already in use 
还是我的使用姿势有问题

**Comment by zanjie1999** [comment]
> > 比如你22端口有个ssh， tcp2ws 22 55555 服务端就完成了,假设服务器ip是1.2.3.4 然后你去客户端 tcp2ws ws://1.2.3.4:55555 222 ssh -p 222 127.0.0.1
> 
> 这里net.Listen("tcp", 222) 然后本地再使用222这个端口连接，不会报这个吗？
> 
> > Address already in use
> > 还是我的使用姿势有问题

你要作为客户端去连接222，而不是监听222，请先搞懂什么是端口监听，什么是连接

**Comment by saberya** [comment]
> > > 比如你22端口有个ssh， tcp2ws 22 55555 服务端就完成了,假设服务器ip是1.2.3.4 然后你去客户端 tcp2ws ws://1.2.3.4:55555 222 ssh -p 222 127.0.0.1
> > 
> > 
> > 这里net.Listen("tcp", 222) 然后本地再使用222这个端口连接，不会报这个吗？
> > > Address already in use
> > > 还是我的使用姿势有问题
> 
> 你要作为客户端去连接222，而不是监听222，请先搞懂什么是端口监听，什么是连接

tcp2ws ws://1.2.3.4:55555 222
你这里实现不就是会在本地监听222端口吗？还是我的理解有问题

**Comment by zanjie1999** [comment]
> > > > 比如你22端口有个ssh， tcp2ws 22 55555 服务端就完成了,假设服务器ip是1.2.3.4 然后你去客户端 tcp2ws ws://1.2.3.4:55555 222 ssh -p 222 127.0.0.1
> > > 
> > > 
> > > 这里net.Listen("tcp", 222) 然后本地再使用222这个端口连接，不会报这个吗？
> > > > Address already in use
> > > > 还是我的使用姿势有问题
> > 
> > 
> > 你要作为客户端去连接222，而不是监听222，请先搞懂什么是端口监听，什么是连接
> 
> tcp2ws ws://1.2.3.4:55555 222 你这里实现不就是会在本地监听222端口吗？还是我的理解有问题 我发现ssh能连接，我看好像是java.net.Socekt的问题 s = new Socket(); s.bind(new InetSocketAddress(222)); s.connect(sa, (int) attachTimeout);时内部报错了

所以你为什么非要让他监听一个已经有其他程序正在使用的端口？换个端口起监听，

**Comment by saberya** [comment]
> 所以你为什么非要让他监听一个已经有其他程序正在使用的端口？换个端口起监听，

场景是我本地要连接1.2.3.4:8000, 但是1.2.3.4与本地网络不通，所以只能通过跳板机，但是跳板机是通过ws透明转发的。我就只能想办法把本地与1.2.3.4:8000的连接转发到跳板机上，现在又没找到有什么办法能监听到本地的报，就卡bug了，这种有什么好的办法吗

**Comment by zanjie1999** [comment]
> > 所以你为什么非要让他监听一个已经有其他程序正在使用的端口？换个端口起监听，
> 
> 场景是我本地要连接1.2.3.4:8000, 但是1.2.3.4与本地网络不通，所以只能通过跳板机，但是跳板机是别人的服务，我改不了，而且是通过ws协议透明转发的。我就只能想办法把本地与1.2.3.4:8000的连接封装成ws转发到跳板机上，现在又没找到有什么办法能监听到本地的包，就卡bug了，这种有什么好的办法吗

那你就将现在占着8000端口的程序关了就行了

**Comment by saberya** [comment]
> 那你就将你本地现在占着8000端口的程序关了就行了

不是...，比如我用你这个监听了本地222端口，然后我要在本地连接1.2.3.4:8000 ，但是如果不指定本地端口，本地就会随机使用一个端口，这样我就监听不到这个连接，无法在本地转发。所以我在连接1.2.3.4:8000是就指定使用本地的222去连接，但是使用222就会报错，说Address already in use 这样能理解了吧

**Comment by zanjie1999** [comment]
> 果不指定本地端口，本地就会随机使用一个端口，这样我就监听不到这个连接，无法在本地转发

简单的说，只需要这样就可以实现端口转发，而无需做多余的事情，比如说固定发出的端口，你只需要管目标端口，防火墙和路由会自动完成剩下的一切：
假设你在使用C，你想访问A的22端口，你可以直接访问B的55555端口，这个55555端口可以是一个nginx服务或者其他支持proxy的http服务器，其中A和B可能是同一台服务器，不要在意这些细节
假设55555没有任何服务 在B上启动服务端 `tcp2ws 22 55555`
假设55555有nginx，则在任意一个端口启动，然后将输出的配置增加到nginx配置中 `tcp2ws 22 15555`

然后在C上启动客户端，或者你局域网有个D，在上面跑也是没问题的 `tcp2ws ws://1.2.3.4:55555 0.0.0.0:222`
然后你就可以使用D的的ip:222或者127.0.0.1:222在C上访问A的22端口
