### ISSUE TITLE
请问支持代理么？

### ISSUE THREAD

**Issue by swimmingchar** [zanjie1999/tcp-over-websocket#6]
因为我的机子上网需要通过squid代理的，没有办法使用全局变量HTTP_PROXY，请问该怎么办呢？

**Comment by swimmingchar** [comment]
我看了golang的websocket模块，里面有proxy的写法，请问我怎么把
var DefaultDialer = &Dialer{
	Proxy:            http.ProxyFromEnvironment,
	HandshakeTimeout: 45 * time.Second,
}
加上呢？

**Comment by zanjie1999** [comment]
那就在启动前 export HTTP_PROXY 咯，只会在当前窗口生效，不要写到配置文件里去

另外欢迎pr，我倒是没有proxy的需求

**Comment by zanjie1999** [comment]
实现了
