### ISSUE TITLE
server模式启动，location后面的地址能否是自动生成的随机32位字符？

### ISSUE THREAD

**Issue by manaphp** [zanjie1999/tcp-over-websocket#9]
2022/12/17 01:25:02 Server Started ws://0.0.0.0:50022 -> 127.0.0.1:22
Proxy with Nginx:
location /Pz3LRoFCiCKe9zXpOJGpvkuhS1qjCC22/ {
proxy_pass http://0.0.0.0:50022/;
proxy_read_timeout 3600;
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "Upgrade";
proxy_set_header X-Forwarded-For $remote_addr;
access_log off;
}

**Comment by zanjie1999** [comment]
其实根本不验证后面的path，你想输入什么都行

**Comment by zanjie1999** [comment]
改为了12位的uuid，为什么是12位呢，因为uuid最后一组连续的字符就是12位 XD
